#!/usr/bin/bash

shopt -s globstar

if (( $# != 1 )); then
    echo "Please provide the path to a bootable image"
    exit 1
fi
vmimg="$1"

startvm() {
    vm --verbose --memory 4G "$vmimg" &
}

fixdns() {
    ssh -q root@develvm "cat > /etc/resolv.conf" << EOF
nameserver 10.38.5.26
nameserver 10.0.2.3
EOF
}

startvm

while ! ssh -q develvm exit; do
    sleep 1
done

echo "Connected"

fixdns

ssh root@develvm mkdir /rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-??-*.rpm root@develvm:/rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-core-??-*.rpm root@develvm:/rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-worker-??-*.rpm root@develvm:/rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-tests-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-ostree-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-selinux-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/python3-osbuild-??-*.rpm root@develvm:/rpm

ssh -q root@develvm dnf install -y /rpm/*

ssh -q root@develvm usermod -aG weldr achilleas
ssh -q root@develvm systemctl start osbuild-composer.socket

ssh -q develvm composer-cli status show

ssh -q root@develvm journalctl -f -u "*osbuild*"

echo "Ready"
wait
