#!/usr/bin/bash

set -eu

(
    cd ../osbuild-composer || exit 1
    echo "Building binaries"
    make build
)

(
    cd ../osbuild || exit 1
    echo "Building osbuild RPMs"
    rm -r ../osbuild/rpmbuild
    make rpm
)


echo "Stopping services"
ssh -q root@develvm systemctl stop "osbuild*"

echo "Copying osbuild-composer binaries to VM"
scp -q ../osbuild-composer/bin/osbuild-{composer,worker} root@develvm:/usr/libexec/osbuild-composer/.
scp -q ../osbuild-composer/bin/osbuild-image-tests root@develvm:/usr/libexec/osbuild-composer-test/osbuild-image-tests

echo "Copying osbuild RPMs to VM"
ssh -q root@develvm rm -rf /rpm
ssh -q root@develvm mkdir /rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-ostree-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-selinux-??-*.rpm root@develvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/python3-osbuild-??-*.rpm root@develvm:/rpm

echo "Installing osbuild"
# ssh -q root@develvm dnf -y remove osbuild
ssh -q root@develvm dnf install -y /rpm/*

echo "Restarting services"
ssh -q root@develvm systemctl restart osbuild-composer.socket
