#!/usr/bin/env bash

set -eu

usage() {
    echo "$0 input_iso output_iso"
    exit 1
}

if (( $# != 2 )); then
    usage
fi

isomount=$(mktemp -d)
kspath=$(mktemp -d)

iso="$1"
newiso="$2"

echo "Mounting ${iso} -> ${isomount}"
sudo mount -v -o ro "${iso}" "${isomount}"

cleanup() {
    sudo umount -v "${isomount}"
    rmdir -v "${isomount}"
    rm -rv "${kspath}"
}

trap cleanup EXIT

ksfiles=("${isomount}"/*.ks)
ksfile="${ksfiles[0]}"
echo "Found kickstart file ${ksfile}"

echo "Appending 'autopart' to ksfile"
ksbase=$(basename "${ksfile}")
newksfile="${kspath}/${ksbase}"
oldks=$(cat "${ksfile}")
cat > "${newksfile}" << EOF
text --non-interactive
zerombr
clearpart --all --initlabel --disklabel=gpt
autopart --nohome --noswap --type=plain
${oldks}
poweroff
EOF
# cp -v "${ksfile}" "${newksfile}"
# printf "\nautopart\n" >> "${newksfile}"

sudo mkksiso -c "" "${newksfile}" "${iso}" "${newiso}"

echo "==== NEW KICKSTART FILE ===="
cat "${newksfile}"
echo "============================"
