#!/usr/bin/env bash

set -uo pipefail

usage() {
    echo "Usage: $0 [UUID | all] [destination]"
    echo
    echo "Download the results of a (finished) compose to [destination]
    (current working directory by default)
    Specify \"all\" as the ID to download all finished jobs.
    "
}

list_finished() {
    echo ":: Available composes (finished/failed only)"
    ssh -q localvm composer-cli compose list finished failed
}


case $# in
    1)
        destination="."
        ;;
    2)
        destination="$2"
        ;;
    *)
        usage
        list_finished
        exit 1
        ;;
esac

uuidarg="$1"

dl() {
    uuid="$1"
    if ! ssh -q localvm composer-cli compose results "${uuid}"; then
        list_finished
        exit 1
    fi

    echo ":: Downloading results for "${uuid}""
    scp localvm:"${uuid}.tar" "$destination"
}

if [[ "$uuidarg" == "all" ]]; then
    for id in $(ssh -q localvm composer-cli --json compose list finished | jq  -r '.[].id'); do
        dl "${id}"
    done
else
    dl "${uuidarg}"
fi
