#!/usr/bin/env bash

set -uo pipefail

usage() {
    echo "Usage: $0 UUID [destination]"
    echo
    echo "Download the results of a (finished) compose to [destination]
    (current working directory by default)
    "
}

list_finished() {
    echo ":: Available composes (finished only)"
    ssh -q localvm composer-cli compose list finished
}


case $# in
    1)
        destination="."
        ;;
    2)
        destination="$2"
        ;;
    *)
        usage
        list_finished
        exit 1
        ;;
esac

uuid="$1"

if ! ssh -q localvm composer-cli compose results "${uuid}"; then
    list_finished
    exit 1
fi

scp localvm:"${uuid}.tar" "$destination"

echo ":: Results for ${uuid} "
