#!/usr/bin/env bash

set -uo pipefail

usage() {
    echo "Usage: $0 [UUID | all] [destination]"
    echo
    echo "Download the image of a (finished) compose to [destination]
    (current working directory by default)
    Specify \"all\" as the ID to download all finished images.
    "
}

list_finished() {
    echo ":: Available composes (finished/failed only)"
    ssh -q localvm composer-cli compose list finished failed
}


case $# in
    1)
        destination="."
        ;;
    2)
        destination="$2"
        ;;
    *)
        usage
        list_finished
        exit 1
        ;;
esac

uuidarg="$1"

dl() {
    uuid="$1"
    if ! ssh -q localvm composer-cli compose image "${uuid}"; then
        list_finished
        exit 1
    fi

    echo ":: Downloading results for ${uuid}"
    # globbing because we don't know the name, but this can get weird if there
    # are other results from the same compose in the directory
    scp localvm:"${uuid}*" "$destination"
    ssh -q localvm rm "${uuid}*"
}

if [[ "$uuidarg" == "all" ]]; then
    for id in $(ssh -q localvm composer-cli --json compose list | jq  -r '.body.finished[].id'); do
        dl "${id}"
    done
else
    dl "${uuidarg}"
fi
