#!/usr/bin/env bash

set -eu

echo ":: Copying blueprints to VM"
scp -r blueprints localvm:

echo ":: Pushing blueprints to composer"
ssh -q localvm composer-cli blueprints push ./blueprints/*

echo ":: Blueprints added:"
ssh -q localvm composer-cli blueprints list
