#!/usr/bin/bash

set -euo pipefail

scriptloc=$(realpath "$(dirname "$0")")
echo "${scriptloc}"
distro="$1"
config="$2"
outputdir=/scratch/VMs/

pushd ../images
go build -o ./bin/build ./cmd/build
popd

sudo -E ../images/bin/build \
    --distro "$distro" \
    --type qcow2 \
    --rpmmd /scratch/rpmmd \
    --store /scratch/osbuild-store \
    --repositories ../images/data/repositories  \
    --output "$outputdir" \
    --config "${config}"
