#!/usr/bin/env bash
#
# Change API in running VM

scriptloc=$(dirname "$0")
develroot=$(dirname "${scriptloc}")
rundir="${XDG_RUNTIME_DIR}/osbuild-vm"

ssh -q localvm sudo systemctl stop '*osbuild*'

set -eu

# Gen certs
mkdir -p "${rundir}/config"
"${develroot}"/vm/gen-certs.sh "${develroot}/vm/openssl.cnf" "${rundir}/config" "${rundir}/config/ca"

# Copy configs to rundir
cp "${develroot}"/vm/config/*.toml "${rundir}"/config/.
mkdir -p "${rundir}/distributions"
rsync -aP --delete "${develroot}"/docker-image-builder/ib-distributions/. "${rundir}"/distributions

# Copy into VM
ssh -q root@localvm mkdir -p /etc/osbuild-composer
rsync -aP --delete "${rundir}"/config/. root@localvm:/etc/osbuild-composer/.
ssh -q root@localvm chmod ugo+rX -R /etc/osbuild-composer/

ssh -q localvm sudo systemctl start osbuild-composer-api.socket osbuild-remote-worker.socket

curl -s -k --cert "${rundir}/config/client-crt.pem" --cacert "${rundir}/config/ca-crt.pem" --key "${rundir}/config/client-key.pem" https://localhost:10443/api/image-builder-composer/v2/openapi | jq '.paths | keys'
