#!/usr/bin/bash

set -eu

osbuildsrc=../osbuild
composersrc=../osbuild-composer

echo "Stopping services"
ssh -q root@localvm systemctl stop "osbuild*"

echo "Copying osbuild-composer sources to VM"
rsync -aP --exclude build --exclude bin --exclude rpmbuild --delete-excluded --delete "${composersrc}" localvm:

echo "Copying osbuild sources to VM"
rsync -aP --exclude build --exclude rpmbuild --delete-excluded --delete "${osbuildsrc}" localvm:

echo "Building binaries"
ssh -q localvm 'cd osbuild-composer && mkdir -p bin && go build -o bin/ ./cmd/osbuild-{composer,worker}'

echo "Building RPMs"
ssh -q localvm 'cd osbuild && git commit . -m "wip" --allow-empty && sudo dnf -y builddep ./osbuild.spec && make rpm'

echo "Installing osbuild-composer"
ssh -q localvm 'cd osbuild-composer && sudo make install'

echo "Installing osbuild"
ssh -q localvm sudo dnf install -y osbuild/rpmbuild/RPMS/noarch/*.rpm

ssh -q localvm sudo rm -f /etc/osbuild-composer/repositories/*
ssh -q localvm sudo mkdir -p /etc/osbuild-composer/repositories
osversion=$(ssh -q localvm "grep -oP '(?<=VERSION_ID=\")[0-9.]+' /etc/os-release")
if [[ "${osversion}" == "8.5" ]]; then
    echo "Setting repo sources for RHEL 8.5"
    ssh -q localvm sudo cp -v osbuild-composer/test/data/repositories/rhel-85.json /etc/osbuild-composer/repositories/rhel-8-beta.json
    ssh -q localvm sudo cp -v osbuild-composer/test/data/repositories/rhel-85.json /etc/osbuild-composer/repositories/rhel-8.json
else
    echo "Setting repo sources for RHEL 8.4"
    ssh -q localvm sudo cp -v osbuild-composer/test/data/repositories/rhel-84.json /etc/osbuild-composer/repositories/rhel-8-beta.json
    ssh -q localvm sudo cp -v osbuild-composer/test/data/repositories/rhel-84.json /etc/osbuild-composer/repositories/rhel-8.json
fi

echo "Restarting services"
ssh -q root@localvm systemctl restart osbuild-composer.socket
