#!/usr/bin/bash

shopt -s globstar

if (( $# != 1 )); then
    echo "Please provide the path to a bootable image"
    exit 1
fi
vmimg="$1"

startvm() {
    vm --verbose --memory 4G "$vmimg" &
}

startvm

while ! ssh -q localvm exit; do
    sleep 1
done

echo "Connected"

ssh root@localvm mkdir /rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-??-*.rpm root@localvm:/rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-core-??-*.rpm root@localvm:/rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-worker-??-*.rpm root@localvm:/rpm
scp -q ../osbuild-composer/rpmbuild/RPMS/x86_64/osbuild-composer-tests-??-*.rpm root@localvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-??-*.rpm root@localvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-ostree-??-*.rpm root@localvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/osbuild-selinux-??-*.rpm root@localvm:/rpm
scp -q ../osbuild/rpmbuild/RPMS/noarch/python3-osbuild-??-*.rpm root@localvm:/rpm

ssh -q root@localvm dnf install -y /rpm/*

ssh -q root@localvm usermod -aG weldr achilleas
ssh -q root@localvm systemctl start osbuild-composer.socket

ssh -q localvm composer-cli status show

ssh -q root@localvm journalctl -f -u "*osbuild*"

echo "Ready"
wait
