#!/usr/bin/bash

set -eu

(
    cd ../osbuild-composer || exit 1
    echo "Building binaries"
    make build
)

(
    cd ../osbuild || exit 1
    echo "Building osbuild RPMs"
    rm -r ../osbuild/rpmbuild
    make rpm
)


echo "Stopping services"
ssh -q root@localvm systemctl stop "osbuild*"

echo "Copying osbuild-composer binaries to VM"
scp -q ../osbuild-composer/bin/osbuild-{composer,worker} root@localvm:/usr/libexec/osbuild-composer/.

echo "Copying osbuild RPMs to VM"
ssh -q root@localvm rm -r /rpm
ssh -q root@localvm mkdir /rpm
scp ../osbuild/rpmbuild/RPMS/noarch/osbuild-??-*.rpm root@localvm:/rpm
scp ../osbuild/rpmbuild/RPMS/noarch/osbuild-ostree-??-*.rpm root@localvm:/rpm
scp ../osbuild/rpmbuild/RPMS/noarch/osbuild-selinux-??-*.rpm root@localvm:/rpm
scp ../osbuild/rpmbuild/RPMS/noarch/python3-osbuild-??-*.rpm root@localvm:/rpm

echo "Installing osbuild"
# ssh -q root@localvm dnf -y remove osbuild
ssh -q root@localvm dnf install -y /rpm/*

echo "Restarting services"
ssh -q root@localvm systemctl restart osbuild-composer.socket
