#!/usr/bin/bash

set -eu

echo "Stopping services"
ssh -q root@localvm systemctl stop "osbuild*"

echo "Copying osbuild-composer sources to VM"
rsync -aP --exclude build --exclude bin --exclude rpmbuild --delete-excluded --delete ../osbuild-composer localvm:

echo "Copying osbuild sources to VM"
rsync -aP --exclude build --exclude rpmbuild --delete-excluded --delete ../osbuild localvm:

echo "Building binaries"
ssh -q localvm 'cd osbuild-composer && mkdir -p bin && go build -o bin/ ./cmd/osbuild-{composer,worker}'

echo "Building RPMs"
ssh -q localvm 'cd osbuild && git commit . -m "wip" --allow-empty && sudo dnf -y builddep ./osbuild.spec && make rpm'

echo "Installing"
ssh -q localvm 'cd osbuild-composer && sudo make install'
ssh -q localvm sudo dnf install -y osbuild/rpmbuild/RPMS/noarch/*.rpm

echo "Restarting services"
ssh -q root@localvm systemctl restart osbuild-composer.socket
