#!/usr/bin/env bash
#
# Sets up and boots installation medium for ostree commit

set -euo pipefail

if (( $# != 2 )); then
    echo "Provide path to a bootable image and an ostree commit tarball"
    exit 1
fi

img="$(realpath "$1")"
tar="$(realpath "$2")"
cd "$(dirname "$0")" || exit

cleanup() {
    rm -r ksfiles
}
trap cleanup EXIT

mkdir -p ksfiles

cp ostree.ks ./ksfiles
cp "${tar}" ./ksfiles

podman build -t local/ostree.ks .
podman run -d --rm -p 8000:80 --name kssrv local/ostree.ks

cleanup() {
    rm -r ksfiles
    podman stop kssrv
}


startvm() {
    mac="FE:0B:6E:22:3D:13"
    qemu-system-x86_64 -enable-kvm -m 4G -drive file="${1}" -cdrom "${2}" -device virtio-net-pci,netdev=n0,mac="${mac}" -netdev user,id=n0,net=10.0.2.0/24
}

drive="$(mktemp -p /scratch/osbuild/tests/ -t ostree-install-test-XXX.img)"
qemu-img create -f qcow2 "${drive}" 5G

cleanup() {
    rm -r ksfiles
    podman stop kssrv
    echo "VM install disk image ${drive} is not removed"
}

echo "Append 'inst.ks=http://192.168.1.113:8000/ostree.ks' to boot params"
startvm "${drive}" "${img}"
