id = "rhel-8-baseos"
name = "rhel-8-baseos"
type = "yum-baseurl"
url = "http://download.devel.redhat.com/rhel-8/rel-eng/RHEL-8/latest-RHEL-8/compose/BaseOS/x86_64/os/"
check_gpg = false
check_ssl = false
system = false
