id = "rhrt"
name = "rhel-rt"
type = "yum-baseurl"
url = "http://download-ipv4.eng.brq.redhat.com/rhel-8/nightly/RHEL-8/RHEL-8.4.0-20210202.n.0/compose/RT/x86_64/os/"
check_gpg = false
check_ssl = false
system = false
