#!/usr/bin/env bash

set -euo pipefail
cd "$(dirname "$0")/.."

if (( $# != 1 )); then
    echo "USAGE: $0 <image-type>"
    exit 1
fi

imagetype="$1"
rundir="${XDG_RUNTIME_DIR}/osbuild-vm"
certdir="${rundir}/config"

distro="fedora-42"
arch=$(ssh -q develvm uname -m)
while read -r line; do
    eval "export ${line}"
done < <(cat ./config/secrets.env)


echo "Reading repos"
repos=$(jq ".\"$arch\"" ../osbuild-composer/test/data/repositories/"$distro".json)
request_file=$(mktemp -d)/osbuild-request.json

echo "Creating request data in ${request_file}"
cat > "${request_file}" << EOF
{
  "distribution": "${distro}",
  "customizations": {
    "users": [],
    "packages": [
      "tmux",
      "vim",
      "zsh"
    ]
  },
  "image_request": {
    "architecture": "${arch}",
    "image_type": "${imagetype}",
    "repositories": ${repos},
    "upload_options": {
      "region": "us-east-1"
    },
    "upload_targets": [
      {
        "type": "aws.s3",
        "upload_options": {
          "region": "us-east-1"
        }
      }
    ]
  }
}
EOF

cat "${request_file}"

curl -k --cert "${certdir}/client-crt.pem" --cacert "${certdir}/ca-crt.pem" --key "${certdir}/client-key.pem" --request POST --header 'Content-Type: application/json' --data @"${request_file}" https://127.0.0.1:10443/api/image-builder-composer/v2/compose
