version: '2.4'
services:
  composer:
    image: local/osbuild-composer
    container_name: org.osbuild.composer
    build:
      context: $OSBUILD_PROJECT_ROOT/osbuild-composer
      dockerfile: ./distribution/Dockerfile-ubi
    volumes:
      - ./config:/etc/osbuild-composer
    networks:
      net:
        ipv4_address: 172.30.0.10

  worker:
    image: local/osbuild-worker
    container_name: org.osbuild.worker
    build:
      context: $OSBUILD_PROJECT_ROOT/osbuild-composer
      dockerfile: ./distribution/Dockerfile-worker
    # override the entrypoint to specify composer hostname and port
    entrypoint: /usr/libexec/osbuild-composer/osbuild-worker org.osbuild.composer:8700
    volumes:
      - ./config:/etc/osbuild-composer
    environment:
      - CACHE_DIRECTORY=/var/cache/osbuild-worker
    privileged: true
    cap_add:
      - MKNOD
      - SYS_ADMIN
      - NET_ADMIN
    networks:
      net:
        ipv4_address: 172.30.0.20
    depends_on:
      - "composer"

  koji:
    image: quay.io/osbuild/koji:v1
    container_name: org.osbuild.koji.koji
    volumes:
      - /tmp/osbuild-composer-koji-test:/share:z
    environment:
      - POSTGRES_USER=koji
      - POSTGRES_PASSWORD=kojipass
      - POSTGRES_DB=koji
      - POSTGRES_HOST=org.osbuild.koji.postgres
    networks:
      net:

  koji-kdc:
    image: quay.io/osbuild/kdc:v1
    container_name: org.osbuild.koji.kdc
    volumes:
      - /tmp/osbuild-composer-koji-test:/share:z
    networks:
      net:

  koji-postgres:
    image: quay.io/osbuild/postgres:v1
    container_name: org.osbuild.koji.postgres
    environment:
      - POSTGRES_USER=koji
      - POSTGRES_PASSWORD=kojipass
      - POSTGRES_DB=koji
    networks:
      net:

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
