#!/usr/bin/env bash

set -eu
cd "$(dirname "$0")"

echo "Generating certifications"
./gen-certs.sh ./openssl.cnf ./config ./config/ca > /dev/null

echo ":: Starting composer and worker containers"
docker-compose up -d composer worker
echo ":: Containers ready"
echo ":: Available paths (cloud API):"
curl -k --cert ./config/client-crt.pem --cacert ./config/ca-crt.pem --key ./config/client-key.pem https://172.30.0.10:9196/api/composer/v1/openapi.json | jq '.paths | keys'
