#!/usr/bin/bash

set -eu

echo "Stopping services"
ssh -q root@develvm systemctl stop "osbuild*"

echo "Copying osbuild-composer sources to VM"
rsync -aP --exclude build --exclude bin --exclude rpmbuild --delete-excluded --delete ../osbuild-composer develvm:

echo "Copying osbuild sources to VM"
rsync -aP --exclude build --exclude rpmbuild --delete-excluded --delete ../osbuild develvm:

echo "Building binaries"
ssh -q develvm 'cd osbuild-composer && mkdir -p bin && go build -o bin/ ./cmd/osbuild-{composer,worker}'

echo "Building RPMs"
ssh -q develvm 'cd osbuild && git commit . -m "wip" --allow-empty && sudo dnf -y builddep ./osbuild.spec && make rpm'

echo "Installing"
ssh -q develvm 'cd osbuild-composer && sudo make install'
ssh -q develvm sudo dnf install -y osbuild/rpmbuild/RPMS/noarch/*.rpm
ssh -q develvm sudo rm /etc/osbuild-composer/repositories/*
ssh -q develvm sudo cp -v osbuild-composer/test/data/repositories/rhel-84.json /etc/osbuild-composer/repositories/rhel-8-beta.json

echo "Restarting services"
ssh -q root@develvm systemctl restart osbuild-composer.socket
