#!/usr/bin/env bash

set -euo pipefail

usage() {
    echo "Usage: $0 CONTAINER_NAME BLUEPRINT TYPE REF"
    echo
    echo "Start an edge installer compose job in the VM."
    echo "Requires a container to serve the commit loaded into podman."
}

list_blueprints() {
    echo ":: Available blueprints"
    ssh -q localvm composer-cli blueprints list
}

list_types() {
    echo ":: Available types"
    ssh -q localvm composer-cli compose types
}


if (( $# != 4 )); then
    usage
    list_blueprints
    list_types
    exit 1
fi

container="$1"
bp="$2"
imgtype="$3"
ref="$4"

port=8989
podman stop commitsrv || true
echo "Starting ${container} container (commitsrv)"
podman run -d --rm -p${port}:8080 --name commitsrv "${container}"

ssh -q localvm composer-cli --json compose start-ostree --url "http://10.0.2.2:${port}/repo" --ref "${ref}" "${bp}" "${imgtype}"
