#!/usr/bin/env bash
#
# Starts a compose, cancels it immediately, and extracts the manifest from the
# cancelled job.

set -euo pipefail

bp="${1}"
imgtype="${2}"

if ! jobout=$(ssh -q develvm composer-cli --json compose start "${bp}" "${imgtype}"); then
    echo "${jobout}"
    exit 1
fi
jobid=$(jq -r '.build_id' <<< "${jobout}")

echo "Started new job ${jobid}"

ssh -q develvm composer-cli compose cancel "${jobid}"
echo "Cancelled ${jobid}"

ssh -q develvm composer-cli compose metadata "${jobid}"
ssh -q develvm tar xvf "${jobid}-metadata.tar" "${jobid}.json" -O | jq . > "${jobid}.json"
ssh -q develvm rm "${jobid}-metadata.tar"
echo "Downloaded manifest ${jobid}.json"
