name = "bug-test"
description = "RHEL for Edge"
version = "0.0.1"
modules = []
groups = []
distro = ""

[[packages]]
name = "yggdrasil"
version = "*"

[[packages]]
name = "k4e-agent"
version = "*"

[[packages]]
name = "dmidecode"
version = "*"

[[packages]]
name = "ipmitool"
version = "*"

[[packages]]
name = "smartmontools"
version = "*"

[[packages]]
name = "file"
version = "*"

[[packages]]
name = "util-linux"
version = "*"

