name = "fiot-main"
description = ""
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "cri-o"
version = "*"

[[packages]]
name = "cri-tools"
version = "*"

[[packages]]
name = "zezere"
version = "*"

[customizations]

[customizations.services]
enabled = ["crio"]
