name = "gnome-term"
description = "gnome terminal"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "gnome-terminal"
version = "*"

[[packages]]
name = "selinux-policy-targeted"
version = "*"

[customizations]
hostname = "jack.vm"

[[customizations.user]]
name = "achilleas"
description = "admin user"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPqEtsCdSozq0DT8sOazpizsBP65Ni6SMqrQA85Wnfs1 achilleas@Jack"
password = "password42"
home = "/home/achilleas"
groups = ["wheel"]
