name = "gnome"
description = "gnome"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "vim-enhanced"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "sudo"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"

[[packages]]
name = "gnome-shell"
version = "*"

[[packages]]
name = "selinux-policy-targeted"
version = "*"

[customizations]
hostname = "jack.vm"

[[customizations.user]]
name = "achilleas"
description = "admin user"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPqEtsCdSozq0DT8sOazpizsBP65Ni6SMqrQA85Wnfs1 achilleas@Jack"
password = "password42"
home = "/home/achilleas"
groups = ["wheel"]
