name = "kernel-debug"
description = "Test image with debug Kernel"
version = "0.0.1"
modules = []
groups = []

[customizations]
hostname = "Kernel-Test"

[[customizations.user]]
name = "admin"
description = "admin user"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIAYU2wzSk9r1l3iOwsvaJXCsfQIUga3xzShZJAM1zHv achilleas@Ruby"
groups = ["wheel"]

[customizations.kernel]
name = "kernel-debug"
