name = "kernel-pkg"
description = "Test image with alt Kernel package (not customization)"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "kernel-debug"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "vim-enhanced"
version = "*"

[customizations]
hostname = "Kernel-Test"

[[customizations.user]]
name = "admin"
description = "admin user"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIAYU2wzSk9r1l3iOwsvaJXCsfQIUga3xzShZJAM1zHv achilleas@Ruby"
groups = ["wheel"]
