name = "mine-no-user"
description = "My own personal blueprint without user. For testing user creation during install time via kickstart."
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "vim-enhanced"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "sudo"
version = "*"

[customizations]
hostname = "no-user.test"
