name = "pkgs"
description = "My Packages"
version = "0.0.1"
modules = []
groups = []

[[packages]]
name = "vim-enhanced"
version = "*"

[[packages]]
name = "tmux"
version = "*"

[[packages]]
name = "zsh"
version = "*"

[[packages]]
name = "sudo"
version = "*"

[[packages]]
name = "syncthing"
version = "*"

[[packages]]
name = "openssh-server"
version = "*"
