name = "plain"
description = "Plain blueprint with user customizations (no packages)"
version = "0.0.1"
modules = []
groups = []

[customizations]
hostname = "boring"

[[customizations.user]]
name = "achilleas"
description = "admin user"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIAYU2wzSk9r1l3iOwsvaJXCsfQIUga3xzShZJAM1zHv achilleas@Ruby"
home = "/home/achilleas"
groups = ["wheel"]
