#!/usr/bin/env bash

set -eu

cd "$(dirname "$0")"

echo ":: Copying blueprints to VM"
ssh develvm mkdir -p blueprints
rsync -aP --delete . develvm:blueprints/.

echo ":: Pushing blueprints to composer"
ssh -q develvm composer-cli blueprints push ./blueprints/*.toml

echo ":: Blueprints added:"
ssh -q develvm composer-cli blueprints list
