name = "rhel-92"
description = "RHEL 9.0 Base Image"
version = "0.0.1"
distro = "rhel-92"

[customizations]
hostname = "rhel90vm"

[[customizations.user]]
name = "achilleas"
description = "admin user"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPqEtsCdSozq0DT8sOazpizsBP65Ni6SMqrQA85Wnfs1 achilleas@Jack"
password = "password42"
home = "/home/achilleas"
groups = ["wheel"]
