name = "user"
description = "User for installer"

[[customizations.user]]
name = "achilleas"
password = "password42"
home = "/home/achilleas"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPqEtsCdSozq0DT8sOazpizsBP65Ni6SMqrQA85Wnfs1 achilleas@Jack"
groups = ["wheel"]
